// Objective-C API for talking to incognito-chain Go package.
//   gobind -lang=objc incognito-chain
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GomobileTxResult;

@interface GomobileTxResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull b58EncodedTx;
@property (nonatomic) NSString* _Nonnull hash;
// skipped field TxResult.Outputs with unsupported type: []incognito-chain/tx.CoinData

// skipped field TxResult.SenderSeal with unsupported type: *incognito-chain/privacy/coin.SenderSeal

@end

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateCoin(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateConvertTx(NSString* _Nullable args, int64_t num, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateOTAReceiver(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateTransaction(NSString* _Nullable args, int64_t num, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileDecryptCoin(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GomobileEstimateTxSize(NSString* _Nullable paramStr, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateBLSKeyPairFromSeed(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateBTCMultisigAddress(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateKeyFromSeed(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGetSignPublicKey(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileHybridDecrypt(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileHybridEncrypt(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileNewKeySetFromPrivate(NSString* _Nullable skStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileRandomScalars(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileScalarMultBase(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GomobileSetConfigs(NSString* _Nullable args, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileSetShardCount(NSString* _Nullable p0, int64_t num, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileSignPoolWithdraw(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

/**
 * VerifyReceivedTx returns the index of the input coin that matches the OTA secret in parameters, or -1 if none
 */
FOUNDATION_EXPORT BOOL GomobileVerifyReceivedTx(NSString* _Nullable paramsJson, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * VerifySentTx returns the index of the input coin that matches the r in parameters, or -1 if none
 */
FOUNDATION_EXPORT BOOL GomobileVerifySentTx(NSString* _Nullable paramsJson, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * signEncode string, signPublicKeyEncode string, amount string, paymentAddress string
 */
FOUNDATION_EXPORT BOOL GomobileVerifySign(NSString* _Nullable args, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
