// Objective-C API for talking to incognito-chain Go package.
//   gobind -lang=objc incognito-chain
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GomobileCoinCache;
@class GomobileCoinInter;
@class GomobileEstimateTxSizeParam;
@class GomobileInitParamsAsm;
@class GomobileSigPubKey;
@class GomobileTokenInnerParams;
@class GomobileTokenParam;
@class GomobileTx;
@class GomobileTxPrivacyInitParams;
@class GomobileTxResult;
@class GomobileTxToken;
@class GomobileTxTokenData;
@class GomobileTxTokenParams;

@interface GomobileCoinCache : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field CoinCache.PublicKeys with unsupported type: []incognito-chain.encodedBytes

// skipped field CoinCache.Commitments with unsupported type: []incognito-chain.encodedBytes

// skipped field CoinCache.AssetTags with unsupported type: []incognito-chain.encodedBytes

// skipped field CoinCache.Indexes with unsupported type: []uint64

@end

@interface GomobileCoinInter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field CoinInter.Version with unsupported type: incognito-chain.printedUintStr

// skipped field CoinInter.Info with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.Index with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.PublicKey with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.Commitment with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.KeyImage with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.SharedRandom with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.SharedConcealRandom with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.TxRandom with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.Mask with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.Value with unsupported type: incognito-chain.printedUintStr

// skipped field CoinInter.Amount with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.SNDerivator with unsupported type: incognito-chain.encodedBytes

// skipped field CoinInter.AssetTag with unsupported type: incognito-chain.encodedBytes

// skipped method CoinInter.ToCoin with unsupported parameter or return types

// skipped method CoinInter.ToCoinV1 with unsupported parameter or return types

@end

@interface GomobileEstimateTxSizeParam : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long numInputCoins;
@property (nonatomic) long numPayments;
// skipped field EstimateTxSizeParam.Metadata with unsupported type: incognito-chain/metadata/common.Metadata

@property (nonatomic) GomobileTokenInnerParams* _Nullable privacyCustomTokenParams;
@end

/**
 * []byte equivalents are by default encoded with base64 when handled by JSON
 */
@interface GomobileInitParamsAsm : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field InitParamsAsm.SenderSK with unsupported type: incognito-chain/privacy/key.PrivateKey

// skipped field InitParamsAsm.PaymentInfo with unsupported type: []incognito-chain.printedPaymentInfo

// skipped field InitParamsAsm.InputCoins with unsupported type: []incognito-chain.CoinInter

// skipped field InitParamsAsm.Fee with unsupported type: uint64

@property (nonatomic) BOOL hasPrivacy;
@property (nonatomic) NSString* _Nonnull tokenID;
// skipped field InitParamsAsm.Metadata with unsupported type: encoding/json.RawMessage

@property (nonatomic) NSData* _Nullable info;
// skipped field InitParamsAsm.Kvargs with unsupported type: map[string]interface{}

// skipped field InitParamsAsm.Cache with unsupported type: incognito-chain.CoinCache

@property (nonatomic) GomobileTokenInnerParams* _Nullable tokenParams;
- (GomobileTxTokenParams* _Nullable)getCompatTxTokenParams;
- (GomobileTxPrivacyInitParams* _Nullable)getGenericParams;
// skipped method InitParamsAsm.GetInputCoins with unsupported parameter or return types

@end

@interface GomobileSigPubKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field SigPubKey.Indexes with unsupported type: [][]*math/big.Int

- (NSData* _Nullable)bytes:(NSError* _Nullable* _Nullable)error;
- (BOOL)setBytes:(NSData* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
@end

@interface GomobileTokenInnerParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull tokenID;
// skipped field TokenInnerParams.TokenPaymentInfo with unsupported type: []incognito-chain.printedPaymentInfo

// skipped field TokenInnerParams.TokenInput with unsupported type: []incognito-chain.CoinInter

// skipped field TokenInnerParams.TokenCache with unsupported type: incognito-chain.CoinCache

@property (nonatomic) long type;
@property (nonatomic) NSString* _Nonnull tokenName;
@property (nonatomic) NSString* _Nonnull tokenSymbol;
@property (nonatomic) BOOL mintable;
- (GomobileTokenParam* _Nullable)getCompatTokenParams;
// skipped method TokenInnerParams.GetInputCoins with unsupported parameter or return types

@end

/**
 * CustomTokenParamTx - use for rpc request json body
 */
@interface GomobileTokenParam : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull propertyID;
@property (nonatomic) NSString* _Nonnull propertyName;
@property (nonatomic) NSString* _Nonnull propertySymbol;
// skipped field TokenParam.Amount with unsupported type: uint64

@property (nonatomic) long tokenTxType;
// skipped field TokenParam.Receiver with unsupported type: []*incognito-chain/privacy/key.PaymentInfo

// skipped field TokenParam.TokenInput with unsupported type: []incognito-chain/privacy/coin.PlainCoin

@property (nonatomic) BOOL mintable;
// skipped field TokenParam.Fee with unsupported type: uint64

@end

@interface GomobileTx : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Basic data, required
 */
@property (nonatomic) int8_t version;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) int64_t lockTime;
// skipped field Tx.Fee with unsupported type: uint64

@property (nonatomic) NSData* _Nullable info;
/**
 * Sign and Privacy proof, required
 */
@property (nonatomic) NSData* _Nullable sigPubKey;
@property (nonatomic) NSData* _Nullable sig;
// skipped field Tx.Proof with unsupported type: incognito-chain/privacy/proof.Proof

// skipped field Tx.Metadata with unsupported type: incognito-chain/metadata/common.Metadata

// skipped method Tx.Hash with unsupported parameter or return types

// skipped method Tx.HashWithoutMetadataSig with unsupported parameter or return types

// skipped method Tx.InitASM with unsupported parameter or return types

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
@end

@interface GomobileTxPrivacyInitParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TxPrivacyInitParams.SenderSK with unsupported type: *incognito-chain/privacy/key.PrivateKey

// skipped field TxPrivacyInitParams.PaymentInfo with unsupported type: []*incognito-chain/privacy/key.PaymentInfo

// skipped field TxPrivacyInitParams.InputCoins with unsupported type: []incognito-chain/privacy/coin.PlainCoin

// skipped field TxPrivacyInitParams.Fee with unsupported type: uint64

@property (nonatomic) BOOL hasPrivacy;
// skipped field TxPrivacyInitParams.TokenID with unsupported type: *incognito-chain/common.Hash

// skipped field TxPrivacyInitParams.Metadata with unsupported type: incognito-chain/metadata/common.Metadata

@property (nonatomic) NSData* _Nullable info;
@end

@interface GomobileTxResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull b58EncodedTx;
@property (nonatomic) NSString* _Nonnull hash;
// skipped field TxResult.Outputs with unsupported type: []incognito-chain.CoinInter

// skipped field TxResult.SenderSeal with unsupported type: *incognito-chain/privacy/coin.SenderSeal

@end

@interface GomobileTxToken : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TxToken.Tx with unsupported type: incognito-chain.Tx

// skipped field TxToken.TokenData with unsupported type: incognito-chain.TxTokenData

- (GomobileTx* _Nullable)getTxNormal;
// skipped method TxToken.Hash with unsupported parameter or return types

// skipped method TxToken.InitASM with unsupported parameter or return types

- (BOOL)setTxNormal:(GomobileTx* _Nullable)inTx error:(NSError* _Nullable* _Nullable)error;
@end

@interface GomobileTxTokenData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TxTokenData.PropertyID with unsupported type: incognito-chain/common.Hash

@property (nonatomic) NSString* _Nonnull propertyName;
@property (nonatomic) NSString* _Nonnull propertySymbol;
@property (nonatomic) NSData* _Nullable sigPubKey;
@property (nonatomic) NSData* _Nullable sig;
// skipped field TxTokenData.Proof with unsupported type: incognito-chain/privacy/proof.Proof

@property (nonatomic) long type;
@property (nonatomic) BOOL mintable;
// skipped method TxTokenData.Hash with unsupported parameter or return types

@end

@interface GomobileTxTokenParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TxTokenParams.SenderKey with unsupported type: *incognito-chain/privacy/key.PrivateKey

// skipped field TxTokenParams.PaymentInfo with unsupported type: []*incognito-chain/privacy/key.PaymentInfo

// skipped field TxTokenParams.InputCoin with unsupported type: []incognito-chain/privacy/coin.PlainCoin

// skipped field TxTokenParams.FeeNativeCoin with unsupported type: uint64

@property (nonatomic) GomobileTokenParam* _Nullable tokenParams;
@property (nonatomic) BOOL hasPrivacyCoin;
@property (nonatomic) BOOL hasPrivacyToken;
// skipped field TxTokenParams.Metadata with unsupported type: incognito-chain/metadata/common.Metadata

@property (nonatomic) NSData* _Nullable info;
@end

FOUNDATION_EXPORT const int64_t GomobileCustomTokenCrossShard;
FOUNDATION_EXPORT const int64_t GomobileCustomTokenInit;
FOUNDATION_EXPORT const int64_t GomobileCustomTokenTransfer;
FOUNDATION_EXPORT const int64_t GomobileHashSize;
FOUNDATION_EXPORT const long GomobileMAX_TRIES_OTA;
FOUNDATION_EXPORT const int64_t GomobileMaxHashStringSize;
FOUNDATION_EXPORT const int64_t GomobileMaxSizeByte;
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxConversionType;
/**
 * TxCustomTokenType        = "t"  // token  tx with no supporting privacy
 */
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxCustomTokenPrivacyType;
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxNormalType;
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxReturnStakingType;
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxRewardType;
FOUNDATION_EXPORT NSString* _Nonnull const GomobileTxTokenConversionType;

@interface Gomobile : NSObject
// skipped variable PRVCoinID with unsupported type: incognito-chain/common.Hash

@end

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateCoin(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateConvertTx(NSString* _Nullable args, int64_t num, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateOTAReceiver(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileCreateTransaction(NSString* _Nullable args, int64_t num, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileDecryptCoin(NSString* _Nullable paramStr, NSError* _Nullable* _Nullable error);

// skipped function EstimateProofSize with unsupported parameter or return types


FOUNDATION_EXPORT BOOL GomobileEstimateTxSize(NSString* _Nullable paramStr, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateBLSKeyPairFromSeed(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateBTCMultisigAddress(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileGenerateKeyFromSeed(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

// skipped function GetCoinInter with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull GomobileGetSignPublicKey(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileHybridDecrypt(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileHybridEncrypt(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GomobileInitConversionASM(GomobileTx* _Nullable tx, GomobileInitParamsAsm* _Nullable params, int64_t theirTime, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GomobileInitTokenConversionASM(GomobileTxToken* _Nullable txToken, GomobileInitParamsAsm* _Nullable params, int64_t theirTime, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT GomobileCoinCache* _Nullable GomobileMakeCoinCache(void);

FOUNDATION_EXPORT NSString* _Nonnull GomobileNewKeySetFromPrivate(NSString* _Nullable skStr, NSError* _Nullable* _Nullable error);

// skipped function NewTxParams with unsupported parameter or return types


// skipped function PointToBytes with unsupported parameter or return types


// skipped function RandBigIntMaxRange with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull GomobileRandomScalars(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GomobileScalarMultBase(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

// skipped function ScalarToBytes with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull GomobileSetShardCount(NSString* _Nullable p0, int64_t num, NSError* _Nullable* _Nullable error);

// skipped function SignNoPrivacy with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull GomobileSignPoolWithdraw(NSString* _Nullable args, NSError* _Nullable* _Nullable error);

/**
 * VerifyReceivedTx returns the index of the input coin that matches the OTA secret in parameters, or -1 if none
 */
FOUNDATION_EXPORT BOOL GomobileVerifyReceivedTx(NSString* _Nullable paramsJson, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * VerifySentTx returns the index of the input coin that matches the r in parameters, or -1 if none
 */
FOUNDATION_EXPORT BOOL GomobileVerifySentTx(NSString* _Nullable paramsJson, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * signEncode string, signPublicKeyEncode string, amount string, paymentAddress string
 */
FOUNDATION_EXPORT BOOL GomobileVerifySign(NSString* _Nullable args, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
