const NUM_COIN_PROPERTIES = 7;
const NUM_PROOF_PROPERTIES = 14;
const ENCODE_VERSION = 0x00;

const SIG_PUB_KEY_SIZE = 33;
const SIG_NO_PRIVACY_SIZE = 64;
const SIG_PRIVACY_SIZE = 96;

export {
    NUM_COIN_PROPERTIES,
    NUM_PROOF_PROPERTIES,
    ENCODE_VERSION,
    SIG_PUB_KEY_SIZE,
    SIG_NO_PRIVACY_SIZE,
    SIG_PRIVACY_SIZE,
};
